spring:
  application:
    name: configserversms
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pradeepjava/microserviceconfig.git
          default-label: master
          timeout: 5
          force-pull: true
          clone-on-start: true

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true