server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  application:
    name: "cardsms"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071"
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh
