server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: "cardsms"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071"
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh
          - info
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "accountsma"
    version: "1.0.0"
    description: "Eazybank cards application"
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG
